# Generated by Django 3.2.4 on 2021-12-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211225_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_pic',
            new_name='stuimg',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_pic',
            new_name='teachimg',
        ),
    ]
